from __future__ import annotations

from abc import abstractmethod

from .port_protocol import PortProtocol


class BaseWatcher(PortProtocol):
    """
    Abstract base class for all file-system watchers.

    The Watcher is responsible for monitoring file-system changes and producing
    domain Event objects. It does not know what happens to the event after it
    places them into the buffer - that is the responsibility of the Dispatcher
    layer. Thus, the Watcher acts as the Producer in a Producer-Consumer pattern,
    while the Dispatcher is the Consumer, and the shared thread-safe buffer serves
    as the conveyor.

    The Watcher runs in its own thread (Watcher Thread) and continuously watches
    all subscribed paths for changes. When a change is detected, it creates a domain
    event object and puts it into a thread-safe buffer that is shared across the main
    pipeline objects - more precisely, it is a common buffer for the Watcher and
    Dispatcher threads.

    Common protocol between Assembler and implementations:
        Each implementation of BaseWatcher, through its requirements() -> Configure
        object, must explicitly declare three key requirements in internal_reqs for
        the correct and coordinated operation:
            - shutdown_event: responsible for graceful shutdown, managed by the common
                ancestor, the upper-layer Observer object, which controls starting/stopping
                and the entire Observer environment (Watcher and Dispatcher).
            - thread_safe_buffer: a shared buffer accessible to both the Watcher and the
                Dispatcher, acting as a pipeline between the threads. The Watcher places
                events there, and they are later processed in the Dispatcher thread.
            - occupied_paths: a shared reference-counting mapping that signals which paths
                are currently being modified by other internal components. Before enqueuing
                any event, the Watcher must check whether the event path is present in
                occupied_paths with a count greater than zero. If so, the event must be
                silently dropped — it was generated by an internal operation (such as
                PathLocker renaming a file) and must not reach the Dispatcher.
        This protocol must never be violated, as it directly affects the operation of
        the Observer daemon.

    Occupied Paths Protocol:
        The Watcher is the only place where occupied_paths filtering occurs. Filtering
        at this stage prevents self-generated events from ever entering the buffer,
        which keeps the buffer clean, reduces memory usage, and spares the Dispatcher
        from processing events it would have to discard anyway.

        Before enqueuing any event into the buffer, the Watcher must check:
            if occupied_paths.get(event.path, 0) > 0:
                skip  # self-generated event, drop silently

        The Watcher must never modify occupied_paths itself — only read it.
        Incrementing and decrementing is the responsibility of the component
        that owns the operation (e.g., PathLocker during acquire/release).
        For the full reference-counting protocol see Configure documentation.

    Path Syntax Protocol:
        All implementations that receive a path from the client must adhere to the
        following protocol to avoid confusing the client:
            /some/path/**             -> recursive: watches path and all its sub-paths.
            /some/path/*              -> non-recursive: watches only the immediate content of the path.
            /some/path or /some/path/ -> without an explicit suffix: must be silently normalized
                                            to /some/path/* by the implementation for non-recursive
                                            watching.

    Why events() is separated from start():
        This is intentional, so that anyone reading and writing the code is not confused
        by unnecessary syntactic noise. start() is responsible for preparing all resources
        before launch - although it does start the thread that wraps events(), its sole
        purpose is to prepare resources (e.g., subscribing to paths). events() then handles
        the actual monitoring and placement of Event objects into the thread-safe buffer.
        This clearly separates responsibilities without mixing them.

    Graceful Shutdown Protocol:
        All implementations of BaseWatcher must respect the shutdown_event flag and
        periodically check whether it is set (shutdown_event is set?), so that when asked
        to stop from above, they can correctly end their session inside events() without
        crashing.

    Implementation examples:
        - InotifyWatcher: Linux, uses the inotify kernel subsystem.
        - FanotifyWatcher: Linux, uses the fanotify kernel subsystem.
        - WindowsWatcher: Windows, uses ReadDirectoryChangesW.
        - PollingWatcher: Cross-platform, uses os.stat() polling.

    Notes:
        - Watcher runs in its own thread (Watcher Thread).
        - It must respect shutdown_event to stop gracefully.
        - It must never block indefinitely without checking shutdown_event.
        - It must never modify occupied_paths — only read it for filtering.
    """

    @abstractmethod
    def start(self) -> None:
        """
        Prepares all necessary resources for watching and starts the main
        event-loop thread.

        This method performs initialization (path subscriptions, opening file
        descriptors/handles, source validation) before spawning the Watcher Thread.
        Immediately after successful setup, it launches the thread in which events()
        runs - the core loop responsible for detecting changes and enqueuing events
        into the thread-safe buffer.

        Called only when observation is about to begin, once the Observer has
        decided to start processing filesystem changes. Calling start() again
        without a prior stop() is not allowed.
        Contains no observation logic itself - purely setup and thread launch.
        """
        ...

    @abstractmethod
    def stop(self) -> None:
        """
        Waits for the Watcher Thread to exit after the shutdown_event has
        been set, then removes or clears all previously prepared
        resources: unsubscribing from paths, closes file descriptors/handles,
        releases kernel watcher, freeing memory and preventing resource leaks.

        Called only when the Observer decides to stop monitoring
        and shut down. Once this method returns, no dangling subscriptions
        or unreleased resources remain guaranteed.
        """
        ...

    @abstractmethod
    def events(self) -> None:
        """
        Core observation loop. Continuously reads file-system changes from
        subscribed sources (inotify, fanotify, ReadDirectoryChangesW, or
        polling results), transforms them into domain Event objects, and
        enqueues them into the shared thread-safe buffer.

        Checks occupied_paths before enqueuing each event — any event whose
        path has an active ignore reference count greater than zero is silently
        dropped and never placed into the buffer.

        Runs inside the Watcher Thread as its main event loop body.
        Executes until shutdown_event is set, after which it exits cleanly
        releasing any ephemeral session resources (system-level subscriptions
        or other resources are not removed here - that is handled by stop()).
        """
        ...
